version: 2
jobs:
  full-u20.04-focal-codecov:
    docker:
      - image: mrpt/mrpt-build-env:full-focal
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ENABLE_COVERAGE=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u20.04
      - run: make -C build-u20.04 tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u20.04
      - run: make gcov -C build-u20.04
      - run: make -C build-u20.04
      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build-u20.04
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u20.04
  full-u21.10-impish:
    docker:
      - image: mrpt/mrpt-build-env:full-u21.10-impish
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u21.10
      - run: make -C build-u21.10 tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u21.10
      - run: make -C build-u21.10
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u21.10
  full-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u18.04
      - run: make -C build-u18.04 tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u18.04
      - run: make -C build-u18.04
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u18.04
  clang-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Generate cmake files
          command: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ENABLE_COVERAGE=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u18.04-clang
          environment:
            CC: /usr/bin/clang-6.0
            CXX: /usr/bin/clang++-6.0
      - run: make -C build-u18.04-clang tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u18.04-clang
      - run: make -C build-u18.04-clang
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u18.04-clang
  headless-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:headless-bionic
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ENABLE_COVERAGE=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u18.04-headless
      - run: make -C build-u18.04-headless tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u18.04-headless
      - run: make -C build-u18.04-headless
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u18.04-headless
  minimal-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:minimal-bionic
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ENABLE_COVERAGE=On -DMRPT_DISABLE_PYTHON_BINDINGS=On -DMRPT_EIGEN_USE_EMBEDDED_VERSION=On -DMRPT_ALLOW_LGPLV3=ON -DCMAKE_VERBOSE_MAKEFILE=ON -H. -Bbuild-u18.04-minimal
      - run: make -C build-u18.04-minimal tests_build_all
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build-u18.04-minimal
      - run: make -C build-u18.04-minimal
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-u18.04-minimal
  clang-format-lint:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - checkout
      - run: apt install clang-format-10 -yq
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: pip3 install --user -r .circleci/python_reqs.txt
      - run:
          name: Run lint task
          command: bash .circleci/check_style.sh
          environment:
            TASK: lint_all
  macos-12.0.0:
    macos:
      xcode: "12.0.0"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: brew update
      - run: brew upgrade
      - run: brew install cmake
      - run: brew install boost
      - run: brew install nasm
      - run: cmake -DMRPT_BUILD_EXAMPLES=On -DMRPT_BUILD_TESTING=On -DMRPT_ENABLE_COVERAGE=On -DMRPT_DISABLE_PYTHON_BINDINGS=On -DMRPT_EIGEN_USE_EMBEDDED_VERSION=On -DCMAKE_VERBOSE_MAKEFILE=ON -DMRPT_ALLOW_LGPLV3=ON -H. -Bbuild-osx
      - run: make -j2 -C build-osx tests_build_all
      - run: make -j2 CTEST_OUTPUT_ON_FAILURE=1 test -C build-osx
      - run: make -j2 -C build-osx
      - persist_to_workspace:
          root: /root/project/
          paths:
            - build-osx
workflows:
  version: 2
  build:
    jobs:
      - full-u20.04-focal-codecov
      - full-u21.10-impish
      - clang-u18.04-bionic
      - headless-u18.04-bionic
      - minimal-u18.04-bionic
      - clang-format-lint
      - macos-12.0.0
